title: 'Terral Lewis - Frontend Developer/Graphic Designer'
author:
  name: 'Terral Lewis'
  email: tldesignsprintandweb@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Personal website for web developer and graphic designer Terral Lewis. Branding, Graphic Design, Strategy, User Experience, Web Development, App Development'
  keywords: 'design, development, branding, marketing, web, print, developer, branding, marketing, web design, web development, graphic design, frontend developer, frontend development, dc, virginia, maryland, digital design, print design, logos, web applications, web apps, user experience, ux, ui, web developer, graphic designer, user centered, javascript, wordpress, css, html, git, angularjs, node, php, adobe creative suite, photoshop, illustrator, indesign, website templates, templates, business templates, flyers, corporate flyers, booklet design, booklets, visual, roadmaps, logos, invitations, frontend developer/graphic designer, website, printdesign'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
header:
  title: 'I''m Terral'
  whatido: 'I Design and Develop for the web and beyond.'
  description: null
copyright:
  -
    line: 'Copyright 2016 Terral Lewis'
social:
  -
    url: 'http://www.facebook.com/tldesignseverything'
    icon: facebook
  -
    url: 'http://www.twitter.com/tldesigns_4u'
    icon: twitter
  -
    url: 'http://www.behance.net/terrallewis'
    icon: behance
  -
    url: 'http://www.instagram.com/tldesigns_everything'
    icon: instagram
twitter:
  id: 749250541969170432
  domId: tw-widget1
  maxTweets: 3
  enableLinks: 'true'
  showInteraction: 'false'
  showImages: 'false'
  showUser: 'false'
